  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - quarkus-lambda-rest-gw-1.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    QuarkusLambdaRestGw:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided
        CodeUri: target/function.zip
        MemorySize: 256
        Policies: 
          - AWSLambdaBasicExecutionRole
          - SNSPublishMessagePolicy:
              TopicName:
                !GetAtt MailTopic.TopicName
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
            topicArn: !Ref MailTopic
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /emails
              Method: POST

    MailTopic:
      Type: AWS::SNS::Topic
      Properties: 
        TopicName: email-topic

  Outputs:
    QuarkusLambdaRestGwNativeApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
      Export:
        Name: QuarkusLambdaRestGwNativeApi
