version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "quarkus-email-api-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o9p6qnwsutlu"
s3_prefix = "quarkus-email-api-stack"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
